alias agupd='sudo apt update && apt list --upgradable'
alias agupg='sudo apt upgrade'
alias agar='sudo apt autoremove'
alias ctop='docker run --rm -ti --name=ctop --volume /var/run/docker.sock:/var/run/docker.sock:ro quay.io/vektorlab/ctop:latest -s name'
alias cat='batcat -Pp'
alias diff='colordiff'
alias fd='fd -H'
alias tv='tv --exact'
alias ds='du -h --max-depth 1'
