set termguicolors
set t_Co=256
set encoding=utf8
let mapleader = " "
colorscheme catppuccin

call plug#begin()

Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'tpope/vim-fugitive'
Plug 'ryanoasis/vim-devicons'
Plug 'preservim/nerdtree'
Plug 'github/copilot.vim'

call plug#end()

let g:airline_powerline_fonts = 1
let g:aurline_theme='dark'

autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 1 && isdirectory(argv()[0]) && !exists('s:std_in') |
    \ enew | execute 'cd '.argv()[0] | execute 'NERDTree' argv()[0] | endif

nnoremap <Leader>e :NERDTreeToggle<CR>
